import random
import strutils
randomize()


var actions = [
  " eating bat",
  " standing in a (phONE booth)",
  " exploding",
  " a ma cambiada/gafas de sol",
  " OD'ing",
  " OEEE OE OE OEEEE...!!!",
  " packed in a car (top secret)",
  " wearing a tuxito and drinking wiskey",
  " Escena el gordo y el flaco",
  " con un pañuelo en la cabeza",
  " Marcando un gol",
  " jugando a tenis",
  " Contando chiste/ zorro",
  " shooting tommy gun",
  " Escribiendo un libro / sermon",
  " writting in a chalk board",
  " riding a motorbike",
  " Mascando una cuerda",
  " heiling",
  " lighting dynamite/ motorbiking",
  " holding a 'yes we can' banner",
  " Doing a 69 with a guitar",
  " eating a carrot",
  " getting a blowjob",
  " playing harmonica / blowing in the wind",
  " champange y putas",
  " riding skateboard",
  " programming a computer",
  " Chasing nude/buxom women",
  " moonwalking",
  " contando un chiste/encanyonandose / on top of a tree",
  " singing / holding shield",
  " missing a bootball",
  " bending cane",
  " riding a turtle/catching butterflies",
  " mascando tabaco",
  " walking along the catwalk",
  " riding a motorbike",
  " ?",
  " patada voladora",
  " memorizing deck /eating DOnut",
  " Taladrandose el cerebro",
  " kicking ball",
  " doing magic",
  " preparando asado",
  " sentado en un dock/ tocando el piano",
  " piloting ship while saluting",
  " scratching",
  " talking with a turtle",
  " ?",
  " Walking like an egyptian (EEOOOEEEOOO, EEEOEEOO)",
  " cuervo en el hombro",
  " american pie? / cantando a saco",
  " guitar-depresivo/ gritando 'hijodeputaaa'",
  " insultando",
  " rapeando",
  " hacking nsa",
  " dropping bomb",
  " follandose a sara montiel/pescando",
  " Kicking niggers",
  " slam dunk",
  " scratch",
  " driving a bus",
  " riding a horse (seguidme, conozco el camino)",
  " smoking joint",
  " eating american pie",
  " guantes de boxeo",
  " ?",
  " Magnifying glass / heroin",
  " Haciendo un 69",
  " in animal farm",
  " X-files",
  " bombing irak / looking through binos in army helmet/tank)",
  " Fent Cafe",
  " ??",
  " Carnaval",
  " Spitting blood",
  " lookin through telescope/ tapando un arbol",
  " strumming Guitar",
  " Good news everyone",
  " Carrying bag of gifts",
  " Laughing / wizard hat",
  " tanning",
  " vomitando rainbows",
  "",
  " sword-and-cat",
  " ?",
  " driving time machine",
  " holding wwe belt",
  " Browsing Hackernews",
  " ?",
  " walking on the moon / Floating with astronaut suit",
  " hand tucked in coat",
  " holding 60sec chrono",
  " riding a snake",
  " ?",
  " standing on a box",
  " Ensenyant els ous",
  " hi-five howImetYourMother",
  " ?",
]

var people = [
  " ozzy osbourne",
  " 01- Neo (“The One”)",
  " obi-wan/obelix/osama bin laden",
  " OC: oscar C.",
  " OD: Amy Winehouse",
  " OE: Fanatico de la Roja",
  " Omar shariff/ omar sy",
  " james bond (pierce)",
  " OH: Oliver Hardy",
  " Olivia Newton john",
  " messi",
  " Andre Agassi",
  " Andreu Buenafuente / Antonio banderas",
  " al capone/Angus young(AC/dc)",
  " Arthur Doyle /Jesus",
  " albert einstein",
  " Arnold Schwarzenaegger",
  " Andre el gigante/antoni gaudi",
  " adolf hitler",
  " AN: Alfred nobel / angel nieto",
  " barak obama",
  " Bryan Adams",
  " Bugs Bunny/BBking",
  " bill clinton",
  " bob dylan",
  " bernie ecclestone",
  " Bart simpson /ben stiller",
  " bill gates",
  " Benny Hill",
  " BN: Michael jackson (blanc/negre)",
  " CO: ConnanOBrian /okasaki/cocochanel/muniente",
  " Christina Aguilera/ Capitan America",
  " charlie brown",
  " charlie chaplin",
  " Charles darwin/celine dion",
  " clint eastwood",
  " claudia schiffer/c.shannon/c.santana",
  " che guevara",
  " Charlton heston/ captain haddock",
  " chuck norris",
  " dominick OBrien /homer simpson",
  " DA: Darren aronofsky",
  " David Beckam /david bisbal",
  " david copperfield",
  " DD: didier",
  " DE: douglas engelbart/ duke elington",
  " Dr.Spock",
  " DG: David guetta",
  " Douglas Hofstadter /david hasselhoff",
  " DN: Don bot / dr. no",
  " EO: Cleopatra",
  " EA: Edgar allan poe",
  " EB: Ellizabeth banks/Enrique bunbyry",
  " Eric clapton / erik cartman",
  " ED: Edsger W. Dijkstra. eddie murphy?",
  " EE: eminem.",
  " Edward Snowden",
  " EG: Enola Gay (airplane)/ed.scisorhands",
  " Ernst hemingway/ ethan hunt",
  " EN: edward norton",
  " shaquille O'Neil",
  " SA: Sterling Archer/ Steve Aoki / Salvador allende",
  " Sandra Bullock",
  " Sean Connery",
  " snoop dog /salvador dali",
  " SE: Shannon elisabeth/ santa's elves",
  " Sylvester Stalone",
  " samwise gamgee/ Seth green",
  " Sherlock Holmes/stephen hawking",
  " SN: sam neil/ Silvia SaiNt",
  " George Orwell",
  " GA: Gillian Anderson",
  " George Bush/mario bros",
  " George Clooney",
  " Gerard Depardieu",
  " Gloria estefan",
  " Gene Simons",
  " Galileo galilei/ gandalf the Grey",
  " George harrison",
  " GN: Professor farnsworth",
  " Santa claus",
  " HA: Joker /Hal Abelson",
  " Halle berry",
  " yo",
  " HD: henry HouDini. high definition",
  " HE: he-man",
  " Han solo / Homer simpson",
  " HG. Wells",
  " Hulk hogan",
  " HN: HaNSolo. Paul Graham",
  " NO: Dr.No",
  " Neil Armstrong",
  " napoleon bonaparte",
  " Nicolas Cage",
  " ND: Jim morrison",
  " NE: Naked elvis?",
  " Nicolas sarkozy",
  " NG: noel galagher",
  " NH: joan gaspart/neil harris",
  " NN: SuperNaNnjy",
]

echo "Hello, I'll try to describe the following number"

var my_num: string = readLine(stdin)

proc showme(numeric_str: string, person: bool) =
  if person:
    echo people[parseInt(numeric_str)]
  else:
    echo actions[parseInt(numeric_str)]

var person = true
while my_num.len > 0:
  if my_num.len >= 2:
    showme(my_num[0..1], person)
    person = not person
  else:
    echo my_num[0]
    break
  my_num = my_num[2..^1]
